name: 'Host Test'
description: 'Run host tests on the project'

runs:
  using: 'composite'
  steps:
    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Run host tests
      shell: bash
      run: ./gradlew :shared:testAndroidHostTest

    - name: Upload host test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: host_test_report
        path: ./shared/build/reports/tests/testAndroidHostTest/