require "net/http"
require "json"

default_platform(:android)

platform :android do
  desc "Distribute a new build to Firebase Distribute"
  lane :distribute do

      event_name = ENV["GITHUB_EVENT_NAME"]
      is_pr = event_name == "pull_request"
      is_push = event_name == "push"

      version_name = if is_pr
          branch_name = ENV["GITHUB_HEAD_REF"] || ""
          branch_name.include?("/") ? branch_name.split("/").join("-") : branch_name
      else
          "dev"
        end

      changelog = ""

      if is_pr
          begin
              repo = ENV["GITHUB_REPOSITORY"]
              token = ENV["GITHUB_TOKEN"]

              pr_number = ENV["GITHUB_REF"]&.match(/refs\/pull\/(\d+)\/merge/)&.[](1) ||
                  ENV["GITHUB_EVENT_PATH"] && JSON.parse(File.read(ENV["GITHUB_EVENT_PATH"]))["pull_request"]["number"]
              uri = URI("https://api.github.com/repos/#{repo}/pulls/#{pr_number}/commits")
              request = Net::HTTP::Get.new(uri)
              request["Authorization"] = "Bearer #{token}"
              request["Accept"] = "application/vnd.github+json"

              response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
                  http.request(request)
              end

              if response.code == "200"
                  commits = JSON.parse(response.body)

                  changelog = commits.map do |c|
                       msg = c["commit"]["message"].lines.first
                       author = c["commit"]["author"]["name"]
                       "* #{msg} (#{author})"
                  end.join("\n")
              else
                  UI.error("GitHub API returned #{response.code}: #{response.body}")
              end
          rescue => e
              UI.error("Failed to build pull request changelog: #{e.message}")
          end
      elsif is_push
          begin
              event = JSON.parse(File.read(ENV["GITHUB_EVENT_PATH"]))

              commits = event["commits"] || []

              changelog = commits.map do |c|
                 msg = c["message"].lines.first
                 author = c["author"]["name"]
                 "* #{msg} (#{author})"
              end.join("\n")

          rescue => e
               UI.error("Failed to build push changelog: #{e.message}")
          end
      end

      UI.message("Branch: #{version_name} | Changelog: #{changelog}")

      gradle(
        task: "assemble",
        build_type: "Release",
        properties: {
            "environment" => "dev",
            "versionNameSuffix" => version_name
        }
      )

      release = firebase_app_distribution(
        app: ENV["APP_ID"],
        service_credentials_file: "firebase_distribution.json",
        release_notes: changelog
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
