name: Build and Distribute APK

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - hotfix/**
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.1.0'

      - name: Run lint
        run: ./gradlew :android:learncast:lintRelease

      - name: Run ktlintCheck
        run: ./gradlew ktlintCommonMainSourceSetCheck ktlintAndroidMainSourceSetCheck

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint_report
          path: ./android/learncast/build/reports/lint-results-release.html

  host-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.1.0'

      - name: Run host tests
        run: ./gradlew :shared:testAndroidHostTest

      - name: Upload host test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: host_test_report
          path: ./shared/build/reports/tests/testAndroidHostTest/

  device-test:
    runs-on: ubuntu-latest
    environment: dev
    needs: [lint, host-test]
    strategy:
      matrix:
        api-level: [30]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.1.0'

      - name: Cache Android system images
        uses: actions/cache@v5
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}/system-images
          key: system-images-${{ runner.os }}-${{ matrix.api-level }}

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Run device tests
        run: ./gradlew :shared:pixel2api30AndroidDeviceTest

      - name: Upload device test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: device_test_report_${{ matrix.api-level }}
          path: ./shared/build/reports/androidTests/managedDevice/androidmain/api-${{ matrix.api-level }}/

      - name: Print disk space usage
        if: failure()
        run: df -h

  deploy-firebase:
    runs-on: ubuntu-latest
    environment: dev
    needs: [device-test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.1.0'

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.10
          bundler-cache: true

      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "firebase_distribution.json"
          fileDir: "./"
          encodedString: ${{ secrets.FIREBASE_DISTRIBUTION_ACCESS_KEY }}

      - name: Distribute a new build to Firebase
        run: bundle exec fastlane distribute
        env:
          APP_ID: ${{ secrets.APP_ID }}
