name: Linting and Testing

on:
  push:
    branches-ignore:
      - main
      - dev
      - hotfix/**

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Run Lint Checks
        uses: ./.github/actions/lint-check

  host-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Run Host Tests
        uses: ./.github/actions/host-test