name: 'Lint Check'
description: 'Run lint and ktlint checks on the project'

runs:
  using: 'composite'
  steps:
    - name: Setup Project
      uses: ./.github/actions/setup-project

    - name: Run lint
      shell: bash
      run: ./gradlew :android:learncast:lintRelease

    - name: Run ktlintCheck
      shell: bash
      run: ./gradlew ktlintCommonMainSourceSetCheck ktlintAndroidMainSourceSetCheck

    - name: Upload lint report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lint_report
        path: ./android/learncast/build/reports/lint-results-release.html